apiVersion: apps/v1
kind: Deployment
metadata:
  name: nicedishy-frontend
spec:
  selector:
    matchLabels:
      app: nicedishy-frontend
  template:
    metadata:
      labels:
        app: nicedishy-frontend
    spec:
      containers:
        - name: nicedishy-frontend
          image: nicedishy-frontend
          imagePullPolicy: IfNotPresent


