apiVersion: v1
kind: Pod
metadata:
  name: nicedishy-migrations
spec:
  volumes:
    - name: migrations
      emptyDir:
        medium: Memory
  restartPolicy: OnFailure
  initContainers:
    - image: migrations-image
      name: migrations-plan
      volumeMounts:
        - name: migrations
          mountPath: /migrations
      args: ["plan"]
      env:
        - name: SCHEMAHERO_DRIVER
          value: postgres
        - name: SCHEMAHERO_SPEC_FILE
          value: /tables
        - name: SCHEMAHERO_OUT
          value: /migrations/plan.yaml
        - name: SCHEMAHERO_URI
          valueFrom:
            secretKeyRef:
              name: my-postgres-secret
              key: uri
  containers:
    - image: migrations-image
      name: migrations-apply
      volumeMounts:
        - name: migrations
          mountPath: /migrations
      args: ["apply"]
      env:
        - name: SCHEMAHERO_DRIVER
          value: postgres
        - name: SCHEMAHERO_DDL
          value: /migrations/plan.yaml
        - name: SCHEMAHERO_URI
          valueFrom:
            secretKeyRef:
              name: my-postgres-secret
              key: uri
