apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr
  namespace: nicedishy
spec:
  encryptedData:
    .dockerconfigjson: AgAmgC1KSpWMnQGMvJD5omJg8uXtQVINgStScn+uWtKATj2Wpk+leXJHBbXpgUlwXiXZ3DP0k6SSXqeP7IM0cQ6R0tBpQMoyuYCwFqXWkYbDhez/4LfFV+H0b9fVeuYpW+6YwcBSQdumBqejhDtWLukbQwXMgVidq2sWMsY7b4gm937v7N7dMBN5AdJYWZWuXcXOCEbFBZhTN89oZYBcb/WgTsgB8BjNhfEFwtTeQ8TKv28VIUlOX5o1uNBjG9KxCTnkJNKu+0KTUsaZ0eBt6Vvd2CUEcNP1IxYXc2HA6NOKHTJKEZ1Dog/EPT2/wyPVnxDYipIQc6tor5r/v45S0fR7hPSGa5bQdGT17sJo7ENH8n8wElMLw7oVsDYzjuZbc+Zaum9jglNhNrRTPRwuEQNu6d4G6Tih7HUNrYQiNYJqa1TY7TrGsr26yf95nVbvTcPYlqmoyToHfUVKWFzwmgnLV/FyuWoiTsyeJgn6ONdBxFGbsTB0xMAYb7ORVQUktOL8sQjFWU1zDM83ZORcNt/Mqnwp4GzO7WwoZtCDEngYYA5GM6aheUXYc9z9GW/GGEBJryRYgbt1LRLB16q7rFJT91B08Tiw01PIZAqWP3/SL8AD9VAhUlJNSST7eZmvO9ihurFVr9nwzi9N0oSPf0UYfwzCyCpgiqlo1B+VYGgJ6lNVuC3FcS9IDYQxYGftWUNerFq6Pa7Lkuvgp6aDAR3bApyj9rbdLWg4vmICBCxFEQzvoxgoeg1sdBk49Jkly6XPoBwiubSQXZCQ+/Zh4B/7966kLjFWWD/bVgKzh/pFUeExDmnOmTSzWDZmRWVW9Q5e1XNlidTM3rJTXQsqq7DXtgbW4PAVgomY893r/HWKYKsh5QRQ7gJGoueUqne0CvHAwQF2nLouppU3SKmOH7fs+LTYEOIitydtEX4V1g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ghcr
      namespace: nicedishy
    type: kubernetes.io/dockerconfigjson