apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nicedishy-grafana
  namespace: nicedishy
spec:
  encryptedData:
    apiKey: AgCCTHRHNc6bX5+s0IJZjPlxC8Ksbmfh2GE5ESc6sEDNLLnJDKyavIMR3pFHwyfU98KITF3luRSk2DL+rThI3/Q2XceCw1bwYQjLzEY7ZUz6EMvC2uUAuQK0IRxlFHNkgIjycRxQDyCTyzSJtldtn3hBg0GRsayAg0/2xIzPY12QXY47Y3nHdNklOxHZiZMjGH1TUJbi1DhiA2MKkr/tkAP99OBa8d3z0nGPCEAaO6B0W7Op8DzOVqqPo7JWNN0xdQn3E9HppJA/9i3AccWhVGz/PJdc1eWWlDbsf/YNiv5SGSvE/3nipmu3mmzahLjZUEDMb7sjSLJi/bWzme9NONWLOaMhtKAKM/SMy1foB58x4F2aNpxJ9NPZWC6O7EZEQ0lKehA5/OmaCqS9Mefy1wAgCtMOZ+6eayBQE/HALLeZqhDSGJxoWFLBp1YVEPAst//Oe1GzzPWJbXuIIYfgzKAsQYEw7rsIJbThG6mt6KEcD8TJiueQ5Ow48FYNrAv2164dbr3RVFImK9nRv76JXLfrHS18bjmuoI8qHn4jka3a5fIPoInmojdqVNcJBXsWiLH+KrPin8ieaeG0LmXXBXNV4b+vN/EQb46p3WyF8vzuZUplTtpcQJely47xYolky+FL5NMIDaHV9nr/kdh4EtwFcu2lzw6fnXZ5dUjha7kGXtjVabO2e0ovvvMZlnmsJX9xGYNhjNlzQyf1qVcUdUEE3zl+4W3m+apwMj68ClqdqhdnqfUh1DpjC7P/+NaWwLTatjbOZGRfUGJoBdEKuIxInNAwpwENKRawmL3rn3964v8F2yj4ab7M
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nicedishy-grafana
      namespace: nicedishy
    type: Opaque