apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nicedishy
rules:
- apiGroups:
  - ""
  resources:
  - services
  - secrets
  - pods/exec
  verbs:
  - get
  - list
  - create
  - patch
  - update
  - delete