apiVersion: v1
kind: Service
metadata:
  labels:
    app: timescale
  name: timescale
  namespace: nicedishy
spec:
  ports:
  - name: timescale
    port: 5432
    targetPort: timescale
  selector:
    app: timescale
  type: ClusterIP