apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: dishy-token
spec:
  database: nicedishy-postgres
  name: dishy_token
  requires: []
  schema:
    postgres:
      primaryKey:
      - token_sha
      columns:
      - name: token_sha
        type: text
        constraints:
          notNull: true
      - name: dishy_id
        type: text
        constraints:
          notNull: true
