---
apiVersion: v1
kind: Service
metadata:
  name: timescale
  labels:
    app: timescale
spec:
  type: ClusterIP
  ports:
  - name: timescale
    port: 5432
    targetPort: timescale
  selector:
    app: timescale
---
apiVersion: v1
kind: Secret
metadata:
  name: nicedishy-timescale
  labels:
    app: timescale
type: Opaque
stringData:
  uri: "postgresql://nicedishy:nicedishy@timescale/nicedishy?connect_timeout=10&application_name=nicedishy&sslmode=disable"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescale
spec:
  selector:
    matchLabels:
      app: timescale
  serviceName: timescale
  template:
    metadata:
      labels:
        app: timescale
    spec:
      containers:
      - name: timescale
        image: timescale/timescaledb-ha:pg14-latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          value: nicedishy
        - name: POSTGRES_PASSWORD
          value: nicedishy
        - name: POSTGRES_DB
          value: nicedishy
        ports:
        - name: timescale
          containerPort: 5432
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - pg_isready -U nicedishy -h 127.0.0.1 -p 5432
          initialDelaySeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - pg_isready -U nicedishy -h 127.0.0.1 -p 5432
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 1
        volumeMounts:
        - name: nicedishy-datadir
          mountPath: /var/lib/postgresql/data

      volumes:
      - name: nicedishy-datadir
        persistentVolumeClaim:
          claimName: nicedishy-datadir

  volumeClaimTemplates:
  - metadata:
      name: nicedishy-datadir
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
