apiVersion: apps/v1
kind: Deployment
metadata:
  name: nicedishy-api
spec:
  template:
    spec:
      containers:
        - name: nicedishy-api
          args: ["api", "--log-level", "debug"]
          env:
            - name: SESSION_KEY
              value: this-is-not-too-secret
            - name: ENCRYPTION_KEY
              value: this-is-32-bytes-and-not-secret!
            - name: API_ENDPOINT
              value: https://nicedishy-api-marccampbell.cloud.okteto.net
            - name: WEB_ENDPOINT
              value: https://nicedishy-marccampbell.cloud.okteto.net
            - name: CLUSTER_ENDPOINT
              value: localhost:30066
            - name: GOOGLE_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: nicedishy-google
                  key: clientId
            - name: GOOGLE_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: nicedishy-google
                  key: clientSecret
            - name: CORS_ALLOW_ORIGIN
              value: https://nicedishy-${OKTETO_NAMESPACE}.cloud.okteto.net
            - name: GOOGLE_REDIRECTURI
              value: https://nicedishy-${OKTETO_NAMESPACE}.cloud.okteto.net/login/callback
            - name: METRICS_DB_URI
              valueFrom:
                secretKeyRef:
                  name: nicedishy-timescale
                  key: uri
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: nicedishy-timescale # we use the same database in dev
                  key: uri
            - name: NICEDISHY_ENDPOINT
              value: http://localhost:3000
            - name: NATS_ENDPOINT
              value: nats://nats:4222
            - name: POSTMARK_SERVER_TOKEN
              value: "$POSTMARK_SERVER_TOKEN"
            - name: POSTMARK_ACCOUNT_TOKEN
              value: "$POSTMARK_ACCOUNT_TOKEN"
            - name: MAILCHIMP_API_KEY
              value: "$MAILCHIMP_API_KEY"
            - name: GRAFANA_API_KEY
              value: "$NICEDISHY_GRAFANA_API_KEY"
            - name: GRAFANA_DATASOURCE_UID
              value: ybmyTGxnz
            - name: NICEDISHY_RETOOL_API_PASSWORD
              value: "$NICEDISHY_RETOOL_API_PASSWORD"
            - name: GRAFANA_ENDPOINT
              value: http://grafana:3000
            - name: WEB_INTERNAL_ENDPOINT
              value: http://nicedishy:3000
            - name: INTERNAL_AUTH_TOKEN
              value: internal-auth-token
