apiVersion: v1
kind: Service
metadata:
  name: nicedishy-docs
  labels:
    app: nicedishy-docs
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: nicedishy-docs
      targetPort: nicedishy-docs
  selector:
    app: nicedishy-docs
