apiVersion: v1
kind: Service
metadata:
  name: nicedishy
  labels:
    app: nicedishy-frontend
  annotations:
    dev.okteto.com/auto-ingress: "true"       
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: nicedishy-frontend
