apiVersion: apps/v1
kind: Deployment
metadata:
  name: nicedishy-frontend
spec:
  template:
    spec:
      containers:
        - name: nicedishy-frontend
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: API_SERVER
              value: "http://localhost:30065"
