apiVersion: apps/v1
kind: Deployment
metadata:
  name: nicedishy-frontend
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: nicedishy-frontend
          image: ghcr.io/marc-campbell/nicedishy-gitops/nicedishy-frontend
          env:
            - name: API_SERVER
              value: "https://api.nicedishy.com"
          ports:
            - name: http
              containerPort: 3000
