apiVersion: v1
kind: Service
metadata:
  name: nicedishy-frontend
  labels:
    app: nicedishy-frontend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: nicedishy-frontend
