apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-proxy
  name: grafana-proxy
  namespace: nicedishy
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: grafana-proxy
  type: ClusterIP