apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: nicedishy
spec:
  chart:
    spec:
      chart: nats
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: nicedishy
      version: 0.16.0
  interval: 5m
  valuesFrom:
  - kind: ConfigMap
    name: nats-values
    valuesKey: values.yaml