apiVersion: apps/v1
kind: Deployment
metadata:
  name: nicedishy-api
  namespace: nicedishy
spec:
  selector:
    matchLabels:
      app: nicedishy-api
  template:
    metadata:
      labels:
        app: nicedishy-api
    spec:
      containers:
      - args:
        - api
        env:
        - name: SESSION_KEY
          value: this-is-not-too-secret
        - name: ENCRYPTION_KEY
          value: this-is-32-bytes-and-not-secret!
        - name: API_ENDPOINT
          value: https://api.nicedishy.com
        - name: WEB_ENDPOINT
          value: https://nicedishy.com
        - name: POSTHOG_KEY
          value: phc_LZECaXf8ccWedmStjxjInSbyjC1LVdlbRrefqaguo9E
        - name: GOOGLE_CLIENTID
          valueFrom:
            secretKeyRef:
              key: clientId
              name: nicedishy-google
        - name: GOOGLE_CLIENTSECRET
          valueFrom:
            secretKeyRef:
              key: clientSecret
              name: nicedishy-google
        - name: CORS_ALLOW_ORIGIN
          value: https://nicedishy.com
        - name: GOOGLE_REDIRECTURI
          value: https://nicedishy.com/login/callback
        - name: METRICS_DB_URI
          valueFrom:
            secretKeyRef:
              key: uri
              name: nicedishy-timescale
        - name: NATS_ENDPOINT
          value: nats://nats.nats.svc.cluster.local:4222
        - name: GRAFANA_API_KEY
          valueFrom:
            secretKeyRef:
              key: apiKey
              name: nicedishy-grafana
        - name: GRAFANA_DATASOURCE_UID
          value: X3auJcxnk
        - name: NICEDISHY_RETOOL_API_PASSWORD
          valueFrom:
            secretKeyRef:
              key: internalApiPassword
              name: retool-secrets
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POSTGRES_URI
          valueFrom:
            secretKeyRef:
              key: uri
              name: nicedishy-timescale
        image: ghcr.io/marc-campbell/nicedishy/nicedishy-api:ac71776
        imagePullPolicy: IfNotPresent
        name: nicedishy-api
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 500Mi
      imagePullSecrets:
      - name: ghcr
      restartPolicy: Always
      serviceAccountName: nicedishy