apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: retool
  namespace: nicedishy
spec:
  chart:
    spec:
      chart: retool
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: retool
        namespace: nicedishy
      version: 4.7.0
  interval: 5m
  valuesFrom:
  - kind: ConfigMap
    name: retool-values
    valuesKey: values.yaml