apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-proxy
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr
      serviceAccountName: nicedishy
      containers:
        - name: grafana-proxy
          image: ghcr.io/marc-campbell/nicedishy/nicedishy-api
          command: ["/grafana-proxy"]
          args: ["run"]
