apiVersion: apps/v1
kind: Deployment
metadata:
  name: nicedishy-api
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr
      serviceAccountName: nicedishy
      containers:
        - name: nicedishy-api
          image: ghcr.io/marc-campbell/nicedishy-gitops/nicedishy-api
          env:
            - name: SESSION_KEY
              value: this-is-not-too-secret
            - name: ENCRYPTION_KEY
              value: this-is-32-bytes-and-not-secret!
            - name: API_ENDPOINT
              value: https://api.nicedishy.com
            - name: WEB_ENDPOINT
              value: https://nicedishy.com
            - name: POSTHOG_KEY
              value: phc_LZECaXf8ccWedmStjxjInSbyjC1LVdlbRrefqaguo9E
            - name: GOOGLE_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: nicedishy-google
                  key: clientId
            - name: GOOGLE_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: nicedishy-google
                  key: clientSecret
            - name: CORS_ALLOW_ORIGIN
              value: https://nicedishy.com
            - name: GOOGLE_REDIRECTURI
              value: https://nicedishy.com/login/callback
            - name: METRICS_DB_URI
              valueFrom:
                secretKeyRef:
                  name: nicedishy-timescale
                  key: uri
            - name: NATS_ENDPOINT
              value: nats://nats.nats.svc.cluster.local:4222
            - name: GRAFANA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nicedishy-grafana
                  key: apiKey
            - name: GRAFANA_DATASOURCE_UID
              value: X3auJcxnk
            - name: NICEDISHY_RETOOL_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: retool-secrets
                  key: internalApiPassword
