apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nicedishy-google
  namespace: nicedishy
spec:
  encryptedData:
    clientId: AgDMAFb+EOn/H54JVSVNJL6OFW9IXTgMph8oaJSfZks1Y01D51p2XMXDNZ2p25keWNZPeNgeDqrxn9PaIGTCwfBK4kwXnmRpLuzGUS13ZbpfOEgF0U9kiXuYeBfKQQK+I9k5CBkvQ7PjZRC6j7tQzyLcb5Fsb3e/t6bO/CzUq2UkzbbG15+yqylQiJ0vmcBIKymw89BRiUn4pSNigjgt6udWOweAbFBQOjJvD1VmmGcJaO+XjCRlDUbn6bXz+7v3ununmOq49aAkFpzv5Ngd1TccomICzAuCnWnPL79Lnlh1YNk9iZuWxF58OpCfuiywWfme3r81dSmaV6z0Ts0S1HYqyGT1MbGYhj2RTKIoZvRaiJl247lomNxH4q6dGAg/DCGKPh7WfOkUt3UH3FaNsm4BAaZjKs0E2s1d1YnxhcskwUH5OZgi/Bcuhy8rzkXVv8R9s27kXB4gK08IJ8yh3ds2xEHmfRFwXsuqm+Emzq0Xxe5rtKW+rrx2M9xNguotT9rbrN5Jlvj1J/E6O5vC6RLFywnZz2m58fLdsLnKU5/w+cAaDMPphu7v8oY0c8kywNMtWaK3h952Mv9svcsUA/DLvtTUXacx5aTXF1Qr9lQEbomqdDK3DlHZUsL/vOcZbsSbvmELMHM49NwDC8PzcDt6L8iepvycah0Th8kLRMN9naOlfcwZtzIhHUrMIQRX5mxWNM2E68P+UrVhQ9dcz3MIRbHQDZHmrWvgt1UOCaDuvfzc0odUtxrT1cV0fppxqJXTI4xlKCVHBqkbbu77LzLaKEi82X54yJE=
    clientSecret: AgBudXGNjSOX5CMPcY2Xf8qugcctNYpszU6kzQvjtdAXOdEvGRnW095mI5ZjTsxPbuOQ865u37eeoL0iHNXmJ16f+GG4m6iRD0VQ3lt7hsmqNioxEcT1DNbtuVrmNNyDJuDfO7TQ4PRuazwyetITgGbAjsC70J8r2G4SjGxOa6kC0OLQMygR+YzjC6ucXIHQ17U6emyrlmTGKIu7chgMbp1t2mwdDiu5j7HSCQlCrQc86qZ24yU3p5WzQ4yp/xXskjntSklPyIMddFH4qHiXsMxDjD+RQd1AfATKTxvYig//te+b5JBGUK1nk4K4UZuW/mhqLWLbXY3ca5C7kC4r0Ro0pdUIpiAE6sbMBCPlW5d+DO6AkzXmk4L/ukby2DQNaLN8i24K43lwp4jRbAZuh7ue89L5OIokAbXQuGpe2VFISMw0JeqTE4djNGdOhWyrW4Ob6Z7L8TXF+n7sT4EkndkEXPW81eqFHUqQJBAJYoyeiL4rXyQuSUwg6IxnHqgQ9n3zmwWbI+uSfwXdNPR5UO6Zj/HMe3AUpydL4hHNrO5Mi7t3oj/lTgHYJomIdC+guWk5YMjpxB2hJ567D48sAs9rA770izKEDRMJ/3A9VzF3WNIAbyfkAPtSGr9HXY6xyDQ6L7DjApgVUMTYUMHGhgEYknDoScp/pJQzogDGXE9yTeQQO2Y8PTIkkiBIVMqFaAFHnoTMy9USZ1feaF9zMhxqaDia7mJKTizs1cK7vieLcT5PcQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nicedishy-google
      namespace: nicedishy
    type: Opaque

