apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nicedishy
resources:
  - ./namespace.yaml
  - ./imagepullsecret.yaml
  - ./google-secret.yaml
  - ./grafana-secret.yaml
  - ../../base
  - ../../../migrations/kustomize/overlays/production
  - ./loadbalancer.yaml
  - ./clusterrole.yaml
  - ./retool.yaml
  - ./retool-secrets.yaml

patches:
  - ./deployment-api.yaml
  - ./deployment-mailer.yaml
  - ./deployment-grafana-proxy.yaml


images:
  - name: ghcr.io/marc-campbell/nicedishy-gitops/nicedishy-api
    newTag: "NEW_TAG"
