apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: retool-secrets
  namespace: nicedishy
spec:
  encryptedData:
    clientSecret: AgAWEh+VPlhQzWeqWQ6YEEzqqRATTPa2/NIeTZ5HjtLfqWGnZoFfO+fwqU1IfFW9AWTjkXp69l95xEtPaBpQ0dyP1fHMrGz6GKIzZ3A1/kkGVWKE2fypo9/WKPJrPsDdCxZB7Aa/bXIzyDSXtIPCrZ/oi7cw03cKQ5KVAuIkjiZO8owVooQSpRqUE5ZMX6vufXwdzbj38Diue2S/eDFspNlK20fAEp7S3cAriJbLEto7uKRmiuMKMMBuRCYDyI0WEStxxBZkuAMWMdxVBj5RtnFeX7lXx+GudjNEdXHqZJBF095L2xiWDoob1wzEAcVnuen9HxYCjNdqJx3h55l2iLq6mAygeewvc5MuHyxseNxff4j9lsJu8bONZkwx1jfn64Ckni5AiC6/vNVXFe1w/9QctiKsuJHAaV9PIHkLQd+PGTbHbZmi4kf5SzBzmqYsj/4uSqzxU5jDAcnGNcqBjqUPY2EH8aXUN7tiXJKMeIaWVKPly41kmd2bwZ0sQST8119GVs/9yePrOhb6PFDtWSxTXdPYABKF/KSPXvlZLWpkkZ99qNYqymySEdc8wBAHAu2d1Ud8mFELMft+ogdzGEWuFXku5huOjlM0huWbml47o+nCBQX41LsO44l34IvFsc16sCWE2le2G/1Kmy6LFv5AJouO53r1WfTPXvvffNpWOXWeOdTaDajc40/xMAAOJmWGGUDApUCRrxZYFHaiUH50XcVRoJjC/+l+hbuvkLW7T++rFw==
    licenseId: AgCXKiAo+nlaJU1JdGDcSwUc73VOG3AHwBGemcQGhnaUnqfBvOGB9VzZCRBcUNTBuKyfOZV4512ZpGoTVHFfPoaxmKSZOrB0R5rnd4wPYwt2Q84K2qz/I9iGBybsIt1XST954SF5Pff7E/wEjj13Km2p9OL/Qug5xRzB3nHvh13RRFNfE5wX2F2btVbSflvmznlQ9pKtK3zpyK/EVTL9QZ0NkWG1gLObcr1ksTHaZ1nHRviL5l8ewQXZ2rM7tImeNG7xgpi2ZXtqLHJ0RElNVyzapGtDv8PuAcUaJHBUDuuNbx5NMAaXyqWzFynHTLw9l3gCaZ3jK08vy5KCJlNtzeJ782Doy3UNrYZJwOZXDMM7EPKwXARmK49xmlkK7nIF7wzjzaz0gRb+8K+hNQDXVfN52KBTh11wZLf9DvyMJyrV80sQFF7to58NJgpGX1x0rCXpW6PtTEgNd/ghSEYTSEKIw/+BOsaevGb64UlbquGlZdHiw0XjdrKj045P8jYf4YAmYRT1BpZOW8YDghhsgc0L7zOuGvVnyj6kwm5NqjbKKTV6DE2/MqKmlBadmm9dOZDIzrRPzBPSUrUQTq4Nz5VswkoRZzO09VNUqES/f8oW4YQGL4ub2eIGSoUpsWMcp8WPdinlWyVPCb4yj3dL7ZE60YhHyvgscq8QiQ8zdJhYy0Cr20bA0qdBJ2ct1dgKJj8QkdXtXuYBcVl8bbgeDVbHbOUAUlGiCFBV6BXQb0b7zd7kLX7HbOne4A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: retool-secrets
      namespace: nicedishy
    type: Opaque

