site_name: NiceDishy
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
nav:
  - 'What is NiceDishy': index.md
  - 'Getting Started': getting-started.md
  - 'Installation Instructions':
    - MacOS: install-macos.md
    - Windows: install-windows.md
  - 'How NiceDishy Works': how-nicedishy-works.md
  - 'Notifications': notifications.md
  - 'Troubleshooting': troubleshooting.md
  - 'FAQ': faq.md
  # - 'Firmwares': firmwares/index.md
  - 'Get Prepared': prepare.md
