apiVersion: apps/v1
kind: Deployment
metadata:
  name: nicedishy-api
spec:
  template:
    spec:
      # volumes:
      #   - name: migrations
      #     emptyDir:
      #       medium: Memory
      # initContainers:
      #   - image: nicedishy-migrations
      #     name: migrations-plan
      #     volumeMounts:
      #       - name: migrations
      #         mountPath: /migrations
      #     args: ["plan"]
      #     env:
      #       - name: SCHEMAHERO_DRIVER
      #         value: postgres
      #       - name: SCHEMAHERO_SPEC_FILE
      #         value: /tables
      #       - name: SCHEMAHERO_OUT
      #         value: /migrations/plan.yaml
      #       - name: SCHEMAHERO_URI
      #         valueFrom:
      #           secretKeyRef:
      #             name: nicedishy-timescale
      #             key: uri
      #   - image: nicedishy-migrations
      #     name: migrations-apply
      #     volumeMounts:
      #       - name: migrations
      #         mountPath: /migrations
      #     args: ["apply"]
      #     env:
      #       - name: SCHEMAHERO_DRIVER
      #         value: postgres
      #       - name: SCHEMAHERO_DDL
      #         value: /migrations/plan.yaml
      #       - name: SCHEMAHERO_URI
      #         valueFrom:
      #           secretKeyRef:
      #             name: nicedishy-timescale
      #             key: uri

      containers:
        - name: nicedishy-api
          args: ["api", "--log-level", "debug"]
          env:
            - name: SESSION_KEY
              value: this-is-not-too-secret
            - name: ENCRYPTION_KEY
              value: this-is-32-bytes-and-not-secret!
            - name: API_ENDPOINT
              value: https://nicedishy-api-marccampbell.cloud.okteto.net
            - name: WEB_ENDPOINT
              value: https://nicedishy-marccampbell.cloud.okteto.net
            - name: CLUSTER_ENDPOINT
              value: localhost:30066
            - name: GOOGLE_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: nicedishy-google
                  key: clientId
            - name: GOOGLE_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: nicedishy-google
                  key: clientSecret
            - name: GOOGLE_REDIRECTURI
              value: https://nicedishy-${OKTETO_NAMESPACE}.cloud.okteto.net/login/callback
            - name: METRICS_DB_URI
              valueFrom:
                secretKeyRef:
                  name: nicedishy-timescale
                  key: uri
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: nicedishy-timescale # we use the same database in dev
                  key: uri
            - name: NICEDISHY_ENDPOINT
              value: http://localhost:3000
