apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
data:
  thanos.yaml: dHlwZTogczMKY29uZmlnOgogIGJ1Y2tldDogdGhhbm9zCiAgZW5kcG9pbnQ6IG1pbmlvOjkwMDAKICBhY2Nlc3Nfa2V5OiBhYmNkZWYxMjM0NTYKICBzZWNyZXRfa2V5OiBhYmNkZWYxMjM0NTY=
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  thanos:
    baseImage: quay.io/thanos/thanos
    version: v0.23.1
    objectStorageConfig:
      key: thanos.yaml
      name: thanos-objstore-config    
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      prom-instance: external
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-pushgateway
  labels: 
    prom-instance: external
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      prom-data: external
  endpoints:
  - port: http
    honorLabels: true