apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-pushgateway
  template:
    metadata:
      labels:
        app: prom-pushgateway
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway:v1.4.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: prom-pushgateway
  labels:
    prom-data: external
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app: prom-pushgateway
